### ISSUE TITLE
Added extra examples in branches.

### ISSUE THREAD

**Issue by haysclark** [Larusso/travis-CI-actionscript-demo#4]
@Larusso I spend the last couple days banging my head against a wall trying to figure out the ins and outs of Flex-Mojos, not to mention sifting though what remains of the original documentation and forums/mailing list question.

I ended up adding 3 branches which might be worth adding to your project.  GitHub does not seem to allow pull request to a new branch.  I think all of the branches are worth keeping or they could be broken out into multiple repos.
## Flex-Mojos 4.0 - [flexmojos_4.0](https://github.com/haysclark/travis-CI-actionscript-demo/tree/) - the project us
- needed to compile FlexSDK 4.5
- used FlexUnit 4.0
- needs a Flash Player work around
- aided by this Adobe tutorial - [Part 1](http://www.adobe.com/devnet/flex/articles/flex-maven-flexmojos-pt1.html), [Part 2](http://www.adobe.com/devnet/flex/articles/flex-maven-flexmojos-pt2.html)
## Flex-Mojos 4.0 with FlexUnit 4.1 - [flexunit_4.1](https://github.com/haysclark/travis-CI-actionscript-demo/tree/flexunit_4.1)
- needed if you want to use 'Rules'
- requires locally installing module
- minor change to pom.xml
## Flex-Mojos 4.0 with FlexUnit 4.1 and Mockito-flex  [mockito-flex](https://github.com/haysclark/travis-CI-actionscript-demo/tree/mockito-flex)
- _the reason why I was doing this in the first place._ :wink: 
- needed another local module
- has AsUnit dependency
- minor change to pom.xml
- has caveat that it doesn't like mocking objects in the Default Package.

Finally, I didn't bother building out the README's for these branches yet. Let me know what you think.

Cheers,
Hays

**Comment by Larusso** [comment]
hmm. I don`t know if the examples would to in a tag rather than a branch.
Regarding flexunit_4.1. You need to install the library locally because no one is hosting the library remotely? Would it not be easier to host it somewhere? This would simplify the usage for mockito and flex 4.5.

You can open up a pull request for the last step and ping me the 2 hashes from where I would need to branch of/tag of the example branches.

**Comment by haysclark** [comment]
yeah. mockito and flexunit are not hosted anywhere else. I'm not sure how to have those libraries hosted. I have not found any resources stating why they are not hosted. 

The flex/flash audience these days seems pretty small so I'm not sure I'd it's worth the effort.

**Comment by Larusso** [comment]
Feel free to change it :)

**Comment by haysclark** [comment]
@Larusso Thanks for giving me push access.  I will need to improve some of the README's but over all they are in pretty good shape.  I took your advice and made a TAG for each branch, and then mapped a GitHub release to each TAG.  There might be some minor issues to sort out but my hope is the majority of knowledge and research has been recorded]. :smile:
